### ISSUE TITLE
 split function needed 

### ISSUE THREAD

**Issue by shilik** [ranvis/php-mecab-ffi#1]
@ranvis 
Thank you for the great project for php8.*. I have been looking a php8 compatible mecab module for quite a long time, but none of them worked until now.

Is there any way to split the string using current project functions? 
if yes, how to do it?

I used your example code snippets, and got the following output.

`: BOS/EOS,*,*,*,*,*,*,*,*
バナナはおやつに入りますか？: 名詞,固有名詞,一般,*,*,*,バナナはおやつに入りますか?,バナナハオヤツニハイリマスカ,バナナワオヤツニハイリマスカ
: BOS/EOS,*,*,*,*,*,*,*,*`
Obviously, the text is not split, is this correct?

if not, would you please add a split function? thank you very much.

**Comment by ranvis** [comment]
The output looks correct in a way. The library itself is working.
Either you haven't installed/specified the right dictionary, or the encoding is not in sync between MeCab, dictionary and input.

mecab-ipadic: https://sourceforge.net/projects/mecab/files/mecab-ipadic/
mecab-ipadic-NEologd: https://github.com/neologd/mecab-ipadic-neologd/

You can check `Tagger->getDictionaryInfo()` output, e.g.:
```php
use Ranvis\MeCab;
use Ranvis\MeCab\IpaDic\FeaturesEn;
...(snip)...
foreach ($tagger->getDictionaryInfo() as $info) {
    $name = $info->getFileName();
    $name = substr($name, strlen(dirname($name, 2)));
    printf("Name: %s, Version: %d, Encoding: %s\n", $name, $info->getVersion(), $info->getCharset());
}
$headNode = $tagger->parseToNode("バナナはおやつに入りますか？");
foreach ($headNode as $node) {
    echo $node->features()[FeaturesEn::READ], "/";
}
echo "\n";
```

My local output:
```
Name: \ipadic\sys.dic, Version: 102, Encoding: UTF-8
*/バナナ/ハ/オ/ヤツ/ニ/ハイリ/マス/カ/？/*/
```

**Comment by shilik** [comment]
@ranvis  Thanks for the quick response.


my output of $tagger->getDictionaryInfo() is as the following:
`
array(1) {
  [0]=>
  object(Ranvis\MeCab\DictionaryInfo)#6 (7) {
    ["fileName":"Ranvis\MeCab\DictionaryInfo":private]=>
    string(64) "/usr/lib/x86_64-linux-gnu/mecab/dic/mecab-ipadic-neologd/sys.dic"
    ["charset":"Ranvis\MeCab\DictionaryInfo":private]=>
    string(4) "UTF8"
    ["size":"Ranvis\MeCab\DictionaryInfo":private]=>
    int(4622888)
    ["type":"Ranvis\MeCab\DictionaryInfo":private]=>
    int(0)
    ["leftAttrsSize":"Ranvis\MeCab\DictionaryInfo":private]=>
    int(1316)
    ["rightAttrsSize":"Ranvis\MeCab\DictionaryInfo":private]=>
    int(1316)
    ["version":"Ranvis\MeCab\DictionaryInfo":private]=>
    int(102)
  }
}
Name: /mecab-ipadic-neologd/sys.dic, Version: 102, Encoding: UTF8
`
dictionary path and encoding seem to be fine.
with this line 
`use Ranvis\MeCab\IpaDic\FeaturesEn;`


I got an error message:
`Uncaught Error: Class "Ranvis\MeCab\IpaDic\FeaturesEn" not found`

There are only two files:PosId.php, PosIdEn.php in IpaDic, what should be done to deal with this problem?

**Comment by ranvis** [comment]
Oh I missed something. The encoding should be OK.
> ",バナナハ...,バナナワ"

"ハ" => "ワ" in the result may indicate that the example sentence itself is registered as a single proper noun in neologd, since it is too famous.
Can you try another sentence, "メカブはおやつに入りますか？"

> Uncaught Error: Class "Ranvis\MeCab\IpaDic\FeaturesEn" not found

I'm sorry, it isn't in released versions yet... `FeaturesEn::READ = 7`.

**Comment by shilik** [comment]
@ranvis 
Finally,I got the output that is correctly segmented. Thank you very much.
``` 
---------------------------
[]
BOS/EOS,*,*,*,*,*,*,*,*
---------------------------
[メカブ]
名詞,固有名詞,一般,*,*,*,MeCab,メカブ,メカブ
---------------------------
[は]
助詞,係助詞,*,*,*,*,は,ハ,ワ
---------------------------
[おやつ]
名詞,固有名詞,一般,*,*,*,おやつ,オヤツ,オヤツ
---------------------------
[に]
助詞,格助詞,一般,*,*,*,に,ニ,ニ
---------------------------
[入り]
動詞,自立,*,*,五段・ラ行,連用形,入る,ハイリ,ハイリ
---------------------------
[ます]
助動詞,*,*,*,特殊・マス,基本形,ます,マス,マス
---------------------------
[か]
助詞,副助詞／並立助詞／終助詞,*,*,*,*,か,カ,カ
---------------------------
[？]
記号,一般,*,*,*,*,？,？,？
---------------------------
[]
BOS/EOS,*,*,*,*,*,*,*,*
```
