### ISSUE TITLE
AJAX call error :Uncaught FFI\\Exception

### ISSUE THREAD

**Issue by shilik** [ranvis/php-mecab-ffi#2]
I tested with php command line, and it worked as expected.
When I made an AJAX call to the server, apache server log showed the following error message.

`Got error 'PHP message: PHP Fatal error:  Uncaught FFI\\Exception: FFI API is restricted by "ffi.enable" configuration directive in /var/www/html/corpus/vendor/ranvis/mecab/src/Env.php:35\nStack trace:\n#0 /var/www/html/corpus/vendor/ranvis/mecab/src/Env.php(35): FFI::cdef()\n#1 /var/www/html/corpus/ngram.php(12): Ranvis\\MeCab\\Env->__construct()\n#2 /var/www/html/corpus/ngram.php(378): wbMecab->__construct()\n#3 {main}\n  thrown in /var/www/html/corpus/vendor/ranvis/mecab/src/Env.php on line 35'`

It seems to be related with ffi module.
Here is a list of php modules I have.  Not sure what problem is it. Have you ever encountered similar error?

`[PHP Modules]
bz2
calendar
Core
ctype
curl
date
dom
exif
FFI
fileinfo
filter
ftp
gd
gettext
hash
iconv
json
libxml
mbstring
mysqli
mysqlnd
openssl
pcntl
pcre
PDO
pdo_mysql
Phar
posix
random
readline
Reflection
session
shmop
SimpleXML
sockets
sodium
SPL
standard
sysvmsg
sysvsem
sysvshm
tokenizer
xml
xmlreader
xmlwriter
xsl
Zend OPcache
zip
zlib

[Zend Modules]
Zend OPcache`

**Comment by ranvis** [comment]
Uh oh, FFI isn't available by default. Configure `ffi.enable=true` in ini settings of the corresponding SAPI.
```
[ffi]
; FFI API restriction. Possible values:
; "preload" - enabled in CLI scripts and preloaded files (default)
; "false"   - always disabled
; "true"    - always enabled
;ffi.enable=preload
```

**Comment by shilik** [comment]
@ranvis 
Yes, I have modified php.ini, in /etc/php/8.3/cli/ ,/etc/php/8.3/apache2/ and /etc/php/8.3/fpm/
'extension=ffi ' is uncommented as well.

using  `php -i` shows that FFI is enabled.

FFI

FFI support => enabled

somehow I still got the same error message. well, maybe I should try system restart than merely `sudo systemctl restart apache2.service`

**Comment by ranvis** [comment]
You should check `phpinfo()` from web server, since it's separate from CLI.

Edit:  in case others may see this, whatever should be restarted depends. FPM if FPM is used, and not web server itself.

FFI
|FFI support|enabled|
|-|-|

|Directive|Local Value|Master Value|
|-|-|-|
|ffi.enable|On|On|

`ffi.enable`, not "FFI support" btw ;)

**Comment by shilik** [comment]
@ranvis After system restart, ajax call works. 
What a magic!! 
Anyway,it's a good lesson for learning FFI. Thank you very much.

**Comment by ranvis** [comment]
No problem. Glad to see that it worked.
